name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Debug APK
      run: gradle assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: Timescam-App-Debug
        path: app/build/outputs/apk/debug/app-debug.apk
